<?php

/**
 *Implements hook_form_alter().
 */

function alterforms_form_alter(&$form, $form_state, $form_id) {

  // Beware of this: comment the following line if you do not want to activate the viewing of the form-ID
  drupal_set_message("Form ID is : " . $form_id);

  // Now we have to test the form editing with form alter.
  // Select an ID from a form within your Drupal Site and
  // change the string in the if as $form_id

if ($form_id == 'contact_message_form_para_pruebas_form'){


  // If you will go to the referenced form, will see
  // the new elements described here within your form. 

  // First Example: new checkbox
  // We have to set a new checkbox for testing.
  // Add a check box. Clear cache and reload the form.
    $form['name'] = array(
      '#type' => 'checkbox',
      '#title' => t('I certify that this is my true name'),
    );

 // Second Example: More dinamics elements with #states properties
 // Now we're gonna to test the dinamic response through
 // the Form API #states, allowing us to create form 
 // elements that change state (show, hide, enable,disable, etc)
 // from conditions. 

  // Hide nick field when the anonymous checkbox is checked.
   $form['nick'] = array(
     '#type' => 'textfield',
     '#title' => t('Put here your nickname, dude'),
     '#states' => array(
     'invisible' => array(
     ':input[name="anonymous"]' => array('checked' => TRUE),
     ),
    ),
   );

 // Uncheck anonymous field when the name field is filled.
  $form['anonymous'] = array(
    '#type' => 'checkbox',
    '#title' => t('Well, I prefer to remain as anonymous'),
    '#states' => array(
    'unchecked' => array(
    ':input[name="name"]' => array('filled' => TRUE),
    ),
   ),
  );

// Debugging zone

// Here you can select what kind of funciont want to use
// to debug your forms: you can use the general var_dump()
// within a drupal_set_message or the kint() method -with 
// a more organized structure and nested options- provided
// by the Kint Module from Devel Module Set.
// Kint has beed added as a dependency. 

// Uncomment the next line and comment the next function
// to not saturate the layout with information and 
// not overload the view

   kint($form);


 
// This message build from var_dump shows on screen all the data
// Related to the form, passed by $form. 
// The position in this script is just after all the elements, at the end.
// You can view all the values on the top of your form. 
// And you'll can take any form element from this function or
// previus, for editing and deleting. 

// Uncomment the next line and comment the previous function
// to not saturate the layout with information and 
// not overload the view

//   drupal_set_message(var_dump($form));


}




}
